//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Regex {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR_Internal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR_Internal() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Regex.SR_Internal", typeof(SR_Internal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternation conditions do not capture and cannot be named. ähnelt.
        /// </summary>
        internal static string AlternationCantCapture {
            get {
                return ResourceManager.GetString("AlternationCantCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternation conditions cannot be comments. ähnelt.
        /// </summary>
        internal static string AlternationCantHaveComment {
            get {
                return ResourceManager.GetString("AlternationCantHaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target array type is not compatible with the type of items in the collection. ähnelt.
        /// </summary>
        internal static string Arg_InvalidArrayType {
            get {
                return ResourceManager.GetString("Arg_InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only single dimensional arrays are supported for the requested action. ähnelt.
        /// </summary>
        internal static string Arg_RankMultiDimNotSupported {
            get {
                return ResourceManager.GetString("Arg_RankMultiDimNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The array cannot contain null elements. ähnelt.
        /// </summary>
        internal static string ArgumentNull_ArrayWithNullElements {
            get {
                return ResourceManager.GetString("ArgumentNull_ArrayWithNullElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot include class \\{0} in character range. ähnelt.
        /// </summary>
        internal static string BadClassInCharRange {
            get {
                return ResourceManager.GetString("BadClassInCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start index cannot be less than 0 or greater than input length. ähnelt.
        /// </summary>
        internal static string BeginIndexNotNegative {
            get {
                return ResourceManager.GetString("BeginIndexNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capture number cannot be zero. ähnelt.
        /// </summary>
        internal static string CapnumNotZero {
            get {
                return ResourceManager.GetString("CapnumNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capture group numbers must be less than or equal to Int32.MaxValue. ähnelt.
        /// </summary>
        internal static string CaptureGroupOutOfRange {
            get {
                return ResourceManager.GetString("CaptureGroupOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count cannot be less than -1. ähnelt.
        /// </summary>
        internal static string CountTooSmall {
            get {
                return ResourceManager.GetString("CountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enumeration has either not started or has already finished. ähnelt.
        /// </summary>
        internal static string EnumNotStarted {
            get {
                return ResourceManager.GetString("EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal conditional (?(...)) expression. ähnelt.
        /// </summary>
        internal static string IllegalCondition {
            get {
                return ResourceManager.GetString("IllegalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AppDomain data &apos;{0}&apos; contains an invalid value or object for specifying a default matching timeout for System.Text.RegularExpressions.Regex. ähnelt.
        /// </summary>
        internal static string IllegalDefaultRegexMatchTimeoutInAppDomain {
            get {
                return ResourceManager.GetString("IllegalDefaultRegexMatchTimeoutInAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal \\ at end of pattern. ähnelt.
        /// </summary>
        internal static string IllegalEndEscape {
            get {
                return ResourceManager.GetString("IllegalEndEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal {x,y} with x &gt; y. ähnelt.
        /// </summary>
        internal static string IllegalRange {
            get {
                return ResourceManager.GetString("IllegalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incomplete \\p{X} character escape. ähnelt.
        /// </summary>
        internal static string IncompleteSlashP {
            get {
                return ResourceManager.GetString("IncompleteSlashP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal error in ScanRegex. ähnelt.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid group name: Group names must begin with a word character. ähnelt.
        /// </summary>
        internal static string InvalidGroupName {
            get {
                return ResourceManager.GetString("InvalidGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument {0} cannot be null or zero-length. ähnelt.
        /// </summary>
        internal static string InvalidNullEmptyArgument {
            get {
                return ResourceManager.GetString("InvalidNullEmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length cannot be less than 0 or exceed input length. ähnelt.
        /// </summary>
        internal static string LengthNotNegative {
            get {
                return ResourceManager.GetString("LengthNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die parsing &quot;{0}&quot; - {1} ähnelt.
        /// </summary>
        internal static string MakeException {
            get {
                return ResourceManager.GetString("MakeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Malformed \\k&lt;...&gt; named back reference. ähnelt.
        /// </summary>
        internal static string MalformedNameRef {
            get {
                return ResourceManager.GetString("MalformedNameRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (?({0}) ) malformed. ähnelt.
        /// </summary>
        internal static string MalformedReference {
            get {
                return ResourceManager.GetString("MalformedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Malformed \\p{X} character escape. ähnelt.
        /// </summary>
        internal static string MalformedSlashP {
            get {
                return ResourceManager.GetString("MalformedSlashP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing control character. ähnelt.
        /// </summary>
        internal static string MissingControl {
            get {
                return ResourceManager.GetString("MissingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nested quantifier {0}. ähnelt.
        /// </summary>
        internal static string NestedQuantify {
            get {
                return ResourceManager.GetString("NestedQuantify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result cannot be called on a failed Match. ähnelt.
        /// </summary>
        internal static string NoResultOnFailed {
            get {
                return ResourceManager.GetString("NoResultOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not enough )&apos;s. ähnelt.
        /// </summary>
        internal static string NotEnoughParens {
            get {
                return ResourceManager.GetString("NotEnoughParens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation is only allowed once per object. ähnelt.
        /// </summary>
        internal static string OnlyAllowedOnce {
            get {
                return ResourceManager.GetString("OnlyAllowedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantifier {x,y} following nothing. ähnelt.
        /// </summary>
        internal static string QuantifyAfterNothing {
            get {
                return ResourceManager.GetString("QuantifyAfterNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The RegEx engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors. ähnelt.
        /// </summary>
        internal static string RegexMatchTimeoutException_Occurred {
            get {
                return ResourceManager.GetString("RegexMatchTimeoutException_Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replacement pattern error. ähnelt.
        /// </summary>
        internal static string ReplacementError {
            get {
                return ResourceManager.GetString("ReplacementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [x-y] range in reverse order. ähnelt.
        /// </summary>
        internal static string ReversedCharRange {
            get {
                return ResourceManager.GetString("ReversedCharRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A subtraction must be the last element in a character class. ähnelt.
        /// </summary>
        internal static string SubtractionMustBeLast {
            get {
                return ResourceManager.GetString("SubtractionMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insufficient hexadecimal digits. ähnelt.
        /// </summary>
        internal static string TooFewHex {
            get {
                return ResourceManager.GetString("TooFewHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many | in (?()|). ähnelt.
        /// </summary>
        internal static string TooManyAlternates {
            get {
                return ResourceManager.GetString("TooManyAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many )&apos;s.  ähnelt.
        /// </summary>
        internal static string TooManyParens {
            get {
                return ResourceManager.GetString("TooManyParens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference to undefined group number {0}. ähnelt.
        /// </summary>
        internal static string UndefinedBackref {
            get {
                return ResourceManager.GetString("UndefinedBackref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference to undefined group name {0}. ähnelt.
        /// </summary>
        internal static string UndefinedNameRef {
            get {
                return ResourceManager.GetString("UndefinedNameRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (?({0}) ) reference to undefined group. ähnelt.
        /// </summary>
        internal static string UndefinedReference {
            get {
                return ResourceManager.GetString("UndefinedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected opcode in regular expression generation: {0}. ähnelt.
        /// </summary>
        internal static string UnexpectedOpcode {
            get {
                return ResourceManager.GetString("UnexpectedOpcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unimplemented state. ähnelt.
        /// </summary>
        internal static string UnimplementedState {
            get {
                return ResourceManager.GetString("UnimplementedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown property &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized control character. ähnelt.
        /// </summary>
        internal static string UnrecognizedControl {
            get {
                return ResourceManager.GetString("UnrecognizedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized escape sequence \\{0}. ähnelt.
        /// </summary>
        internal static string UnrecognizedEscape {
            get {
                return ResourceManager.GetString("UnrecognizedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized grouping construct. ähnelt.
        /// </summary>
        internal static string UnrecognizedGrouping {
            get {
                return ResourceManager.GetString("UnrecognizedGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterminated [] set. ähnelt.
        /// </summary>
        internal static string UnterminatedBracket {
            get {
                return ResourceManager.GetString("UnterminatedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterminated (?#...) comment. ähnelt.
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
    }
}
